const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const pageNotFound = require("./middleware/404_middleware");
const homePage = require("./routes/home/homePage");
const user = require("./routes/users/user.route");
app.use(express.static("public"));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(homePage, user);
app.use(pageNotFound);
module.exports = { app };
